// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// to regenerate this file for your Firebase project.
//
// ⚠️ THIS IS A PLACEHOLDER — replace with your actual firebase_options.dart
// generated by running `flutterfire configure` after creating a Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwo-zL3Zmji06w6niGHaRgxEiZisXZa20',
    appId: '1:903789237358:android:666e33ec693d62e43b027f',
    messagingSenderId: '903789237358',
    projectId: 'dadumodaretor',
    storageBucket: 'dadumodaretor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwo-zL3Zmji06w6niGHaRgxEiZisXZa20',
    appId: '1:903789237358:ios:666e33ec693d62e43b027f',
    messagingSenderId: '903789237358',
    projectId: 'dadumodaretor',
    storageBucket: 'dadumodaretor.firebasestorage.app',
    iosBundleId: 'com.sayedulmarsalin.dadumodaretor',
  );
}
